Add support for Huntsman v2 TKL
1kc/razer-macos pull request #573
Opened 2022-02-18 10:56 UTC by PrivateiFox

Hi, I've added support for the Razer Huntsman v2 TKL in librazermacos, and I've noticed it's missing here as well.

Since the device is basically the same as the regular Huntsman v2 TKL, I've added support for it based on the features that device had.

I've tested the changes with a custom build -  the keyboard is detected properly, and all light effects seem to work just fine.

Thank you for all of your work on this program.

2022-02-18 16:12 UTC, WrathofthePast requested changes
Please review. If you are good with my suggested changes, lmk and I'll commit them.

2022-02-18 16:12 UTC, WrathofthePast commented on src/devices/huntsman_v2_tkl.json
> +  "image": "https://assets3.razerzone.com/02qciF5cWDrRcrL9CxzbHC017No=/500x500/https%3A%2F%2Fhybrismediaprod.blob.core.windows.net%2Fsys-master-phoenix-images-container%2Fhb8%2Fhd7%2F9239675600926%2F
```suggestion
  "image": "https://dl.razerzone.com/src/5638/5638-1-en-v1.png",
```
This link is much shorter and the one openrazer used.

2022-02-18 16:26 UTC, PrivateiFox commented on src/devices/huntsman_v2_tkl.json
> +  "image": "https://assets3.razerzone.com/02qciF5cWDrRcrL9CxzbHC017No=/500x500/https%3A%2F%2Fhybrismediaprod.blob.core.windows.net%2Fsys-master-phoenix-images-container%2Fhb8%2Fhd7%2F9239675600926%2F
The suggested changes look good to me, thanks

2022-02-18 16:28 UTC, WrathofthePast approved these changes

2022-02-20 21:45 UTC, PrivateiFox commented
I've changed the number of cols for the "ripple" and "wheel" effects. it now matches the cols setting of the Huntsman TE, and looks better.

2022-03-13 14:54 UTC, merged